language: node_js
node_js:
  - '4.1'
  - '0.12'
script:
  - npm test
notifications:
  slack:
    rooms:
      secure: qTCVKPpkKuqKxOvrQ74/M3nBTDHdxUnVz8jucD1z5LtbarSoEAO6kB3jfam/ZSG2TWgS7XThpT/2i6v5EN3pwG3LaAuqaInNreFXvF6KIVCtr2L1griNx2E/rhzL7W9imIuVUKWCYcH1iiMttYJah/7p4EE9jtt5VbJIv1ta7f0BkEsh3zIOK2jL3nswjSp3QAiLsh1atdG/5ylyMHxOCiCm/+DWEvehmzDKKIT3a+56OAcd8P4eScxWImU3Fxpc38xfBfUiZoo9A+A/CoOLbTFbzcYwnD5UBPhkIuZWjnsXQ3nenOHfNCKJuHogvPrYPbhDiOBlGATxbe1Y234LEaGhiUPIgUOJbYA8RcE0GrkWSF8YMaWst7kt4nvja9HQzKTMPC5nTV0g4XBIO+mTzo/vriLCJVwPNNcChLu8XDVlgz7MIA+xvPCLLXAfYd4sraPrgibV2cnkXeodiClQKRrdZpdL9jLrlrbgXj6xQGtWPa18y8f8oMHtJgM/us+eTIbybawOr0RECy2+0Hhm/4ZzNj/qH5w6mMkh/oTZSw6pVFHC3NuN0qEzHxYxCjbXVRqaY+Cw5nBrt5ikVLlyvnX3qPnH1jObX1iR1CTHcYGj4riMPGX/CFhiwhEIbHqNBfXKc4weoS1EPuuqLDt8zc0wEIuCFx49gS7KC0ij63Y=
